name: Commit Conventions, Signing, and Sign-off

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  dco_check:
    runs-on: ubuntu-22.04
    name: DCO
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
    steps:
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@198af03565609bb4ed924d1260247b4881f09e7d
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: DCO Check
      uses: tim-actions/dco@f2279e6e62d5a7d9115b0cb8e837b777b1b02e21
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
      env:
        ACTIONS_STEP_DEBUG: true

  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5.4.1
        env:
          ACTIONS_STEP_DEBUG: true

  validate_pr_title:
    name: Validate PR title
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_STEP_DEBUG: true